version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: champart_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: champart123
      MYSQL_DATABASE: champart_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Database:/docker-entrypoint-initdb.d
    networks:
      - champart_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    container_name: champart_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      MYSQL_ROOT_PASSWORD: champart123
      MYSQL_DATABASE: champart_db
      MYSQL_USER: root
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - champart_network

volumes:
  mysql_data:

networks:
  champart_network:
    driver: bridge