version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: champart_mysql
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Database:/docker-entrypoint-initdb.d
    networks:
      - champart_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build: .
    container_name: champart_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      TOKEN_SECRET_KEY: ${TOKEN_SECRET_KEY}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      CRON_SECRET_KEY: ${CRON_SECRET_KEY}

    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - file:/media
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - champart_network

  cron:
    build: ./cron
    container_name: champart_cron
    restart: always
    environment:
      - CRON_SECRET_KEY=${CRON_SECRET_KEY}
    depends_on:
      - app
    networks:
      - champart_network
volumes:
  mysql_data:
  file:


networks:
  champart_network:
    driver: bridge